### ISSUE TITLE
handleCoords() bug

### ISSUE THREAD

**Issue by moimikey** [moimikey/surger#108]
runtime error that happens on occassion when `handleCoords` tries to manipulate a `lat`/`lng` object that doesn't have a `lat`/`lng` due to API miscommunication.

```
/Users/mshertzberg/.nvm/versions/node/v6.8.1/lib/node_modules/surger/lib/index.js:90
      var _ref$lat = _ref.lat;
                         ^

TypeError: Cannot read property 'lat' of undefined
    at Surger.handleCoords (/Users/mshertzberg/.nvm/versions/node/v6.8.1/lib/node_modules/surger/lib/index.js:90:26)
    at /Users/mshertzberg/.nvm/versions/node/v6.8.1/lib/node_modules/surger/lib/index.js:170:58
```

**Comment by moimikey** [comment]
fixed
